### PR TITLE
Improve TC visibility

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
### Summary
- Added the possibility to focus a tab directly by accessing a link with a fragment at the end [ eg. http://neve-dev.local/wp-admin/themes.php?page=tiob-starter-sites#library ]
- Added the notification that will be displayed in neve dashboard
- Added a new subpage that links directly to My library

### Test instructions
- If this plugin is activated and you have the Agency plan, there will be a notice in the dashboard with a link to My Library. The notice is visible until you press the button that takes you to the TC My Library tab. After that, the notice will be dismissed. See if this works well.
- There should be a [link](https://user-images.githubusercontent.com/52494172/114676520-08f24780-9d12-11eb-97c2-a9bdf28d4764.png) that takes you to the My Library tab. See if it works well.
- See if you can navigate directly to a tab by pasting the link directly into the address bar.

Closes Codeinwp/neve-pro-addon#1286.

### CODE REVIEW

**Comment by tudor-themeisle** [comment]
My Library tab is inactive if you have selected first the Starter Sites tab https://www.loom.com/share/68a897ec604043428524c47620d48083

**Comment by irinelenache** [comment]
@cristian-ungureanu 

- [ ] Nothing happens when i click this button https://prnt.sc/11vgjuj
- [ ] When My library tab is opened, the Starter sites tab appears as active in the left https://prnt.sc/11vgqek
- [ ] As Tudor mentioned, if i'm on the Starter Sites tab, i can't access the My library section via the menu in the left

**Comment by cristian-ungureanu** [comment]
@irinelenache, I forgot to mention that you need to have this version of neve https://github.com/Codeinwp/neve/pull/2772

**Comment by irinelenache** [comment]
@cristian-ungureanu the issues that i mentioned are fixed 👍 
Found a small thing, maybe it can be fixed:
When i switch between **Starter sites** and **My library** tabs, the links from the submenu in the left are different than the links from the Templates Cloud menu
If i switch using these links: https://prnt.sc/11x1f18 , https://prnt.sc/11x1g3b , the page **doesn't refresh**, but if i use these links https://prnt.sc/11x1gvt , https://prnt.sc/11x1o7p , the page **refreshes** (only when i swiitch from My library to Starter sites)

**Comment by cristian-ungureanu** [comment]
Thanks, @irinelenache, you are right but I cannot fix this.

**Pull request merged**
