### PR TITLE
fix: solve issue on new versions of estatik

### LINKED ISSUE #200: Bug: Estatik import
### Description:

It looks like the newer versions of Estatik hook on plugin activation and do a hard redirect that will break the install process. 

### How to reproduce:

1. Import Real Estate Agency on a fresh instance
2. Check that the install breaks

Note: the plugin will install and activate so if you refresh and try again it will import the Demo
### Expected behavior:
Not break on the first install.

### Current behavior:
Break on the first install.

### Technical info
* WordPress version: x.x.x
* Theme version: x.x.x

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Fixes activation issues for the Estatik plugin used inside Real Estate Agency

### Test instructions

1. Import Real Estate Agency
2. Check the import works as expected.

Closes #200.

### CODE REVIEW

**Review by abaicus — APPROVED** [review]

**Comment by irinelenache** [comment]
@preda-bogdan Tested and the issue is fixed but i see that i cannot import the **Coding school** demo, both with or without this PR. Maybe it can be fixed here. You can check on this instance:
```
 Admin area URL: https://carecompetition.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: 1mNkj3QPWKY 
```

**Comment by preda-bogdan** [comment]
@irinelenache thank you for finding this, It was an issue with the listing from demo sites and with the API changes, the issue should be solved once I merge this: https://github.com/Codeinwp/demo-data-exporter/pull/143

**Comment by irinelenache** [comment]
@preda-bogdan All demos work fine for me now, thank you 🚀 

@purplecodes @MarinescuLucia Can you also check if the issue is fixed for you too? For me most of the demos worked fine before the PR so i'll need your confirmation 🙏

**Comment by preda-bogdan** [comment]
@irinelenache thank you for looking into this, I tested also and could not find other issues tested some random free and pro demos, I will prepare a release to solve the Estatik plugin we can create separate PRs for other issues if required.

**Comment by MarinescuLucia** [comment]
@preda-bogdan @irinelenache Sorry to say this, but it still doesn't work for me 🥲 I created multiple instances, on both tastewp and instawp. None of the Elementor templates can be imported for me and some of the Gutenberg ones (for example Recipes Blog, NFT Illustrator, Real Estate Agency, Jewellery Shop, University, Job Board, Resume 2, Architecture Studio) throw that error as well.

Here is a tastewp instance:
 Admin area URL: https://thinkvan.s2-tastewp.com/wp-admin 
 Username: luciamarinescu 
 Password: E81uztgmrdc 

And a instawp instance, even if there is no difference regarding the behaviour between them:
URL : https://us-opossum-reva.instawp.xyz
Username : lijifiyosa8810
Password : tYjLXNDK5TqwBzJRxUHl

**Comment by preda-bogdan** [comment]
@MarinescuLucia The issue should be resolved now for everybody. I've checked on the instances you provided. Can you confirm you have no other issues now?

Thank you!

**Comment by MarinescuLucia** [comment]
@preda-bogdan Yes, it works properly for me now. Thanks! I'm curious, what was causing this?

**Comment by MarinescuLucia** [comment]
I just saw the PR with the license check issue, so it's all good, I understood what was the problem. Thank you!

**Comment by preda-bogdan** [comment]
It was tied to the type of license being used so that's why it worked for some and others not.

**Pull request merged**
