### PR TITLE
Feat: improve Templates Cloud to better showcase as an independent plugin

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Moved "My Library" to a new location under the "Templates Cloud" menu. (pic. 1)
Introduced a new page "Settings" under the "Templates Cloud" menu. This page now holds the activation for the plugin and the feedback form. (pic. 1)
CSS style changes in line with the new Design from Figma. (pic. 3)
Fixed issue with the `<Popover />` component on the new versions of WordPress
Fixed E2E tests

The new menu items ( "My Library" and "Settings" ) are displayed for all users with `manage_options` capability since Saving to the Library is also available for these users.

"Starter Sites" and "Page Templates" remain with  `plugin_activation` capability as they will require the user to be able to install and activate plugins/themes if the Starter Site or Template requires them.

### Screenshots

<details open>
    <summary>New Menu layout w. Neve (pic. 1)</summary>

image 
image
</details>

<details>
    <summary>New Menu layout w./o. Neve (pic. 2)</summary>

image
</details>

<details>
    <summary>Settings page (pic. 3)</summary>

image
image

</details>

### Test instructions

**I. Test using Neve Free**
1. On a fresh instance with Neve, add the Templates Patterns Collection plugin
2. Check the new menu locations (pic. 1)
3. Check that "My Library" is not accessible if no License is provided and that it will redirect to the License activation page from "Settings" when the "I already have a key" link is clicked.
4. Activate using a Neve Pro Key or a Templates Cloud Key
5. Check that the Library is available
6. Check that on a new Post you can Import a template from the Library using the Templates Cloud Block
7. Check the Feedback Form from "Settings"
8. Check the links present on the "Settings" page. (Useful Links)
9. Check the Starter Sites and Page Templates work as before

**II. Test using Neve Pro**
1. On a fresh instance with Neve and Neve Pro where Neve PRO is activated, install the Templates Patterns Collection plugin
2. Check that the Starter Sites and Page Templates work as before
3. Check that "My Library" is already accessible and works as before from the new location.
4. Check that on a new Post you can Import a template from the Library using the Templates Cloud Block
5. Check the White Label feature interacts and works as before with the Templates Patterns Collection plugin

**III. Test using a different theme, other than Neve**
1. On a fresh instance without Neve, add the Templates Patterns Collection plugin
2. Check all the steps from **test case I** except point 9. which does not apply here.
3. Instead of point 9 check that Starter Sites and Page Templates don't appear in the Appearance menu.

Closes codeinwp/templates-cloud#74.

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]

**Comment by irinelenache** [comment]
@preda-bogdan Nice work 🚀 Tested and found only some small things:

- [ ] The **Starter sites** and **Page templates** are still available in the Appearance submenu when other theme is activated https://vertis.d.pr/i/D8n5zi Is this expected?
- [ ] Without Neve, i'm still getting the `lodash is not defined` console error and TPC is not available in the Gutenberg editor https://vertis.d.pr/i/tCr66e Probably the fix is not pulled from development

**Comment by preda-bogdan** [comment]
@irinelenache thank you for checking this, I've merged the changes from development so that the lodash issue is resolved now. I also double-checked the requirements and now hide the `Starter sites` and `Page Templates` when Neve is not present.

Let me know if now everything is working as expected.

**Comment by irinelenache** [comment]
@preda-bogdan Everything's working fine now, thank you ✔️

**Comment by preda-bogdan** [comment]
@irinelenache Thank you for your prompt checking of this!

**Pull request merged**
