### PR TITLE
Fse template import

### LINKED ISSUE #255: Evaluate effort of implementing WP FSE templates inside TPC.
### What problem does this address?

This should allow users to import FSE templates and save FSE templates using TPC.

Challenges:
- We need to allow saving templates from FSE Editor and save metadata as options.
- Change the TPC endpoint to allow a new category for `fse-templates`, this includes saving, listing, and updating.
- Restrict `fse-templates` import for FSE Editor.

Issues that we would need to account for are that we might need to limit templates to specific themes as blocks and other template parts are tied to the theme being available.

Other considerations are tied to importing the templates, it might require a different workflow than the one we are using for the regular templates as we would replace the whole template instead of only adding some blocks.

Maybe having a designated region inside the sidebar when in FSE Editor context would be better, similar to the section we use for saving.

As a first assessment, I would evaluate the effort as a 3 or 4. While it is possible to do there still are some challenges that are not very clear.

### What is your proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
### Summary
- Implemented the FSE Template import inside the templates cloud

> [!NOTE]  
> For the images to be properly saved, the website needs to be public, else it will default to a placeholder image when saving the template.

### Screenshots
<details open>
    <summary>FSE Library</summary>

image
</details>

<details open>
    <summary>FSE Import</summary>

image
</details>

### Test instructions
1. Use this version of the plugin
2. Use a FSE Theme
3. From the FSE Editor, save a template for the Front Page or any other page
4. Check that the template is visible inside My Library
5. Check that the Preview is visible before importing inside the Editor
6. Import the template on a different FSE Theme

Closes #255.

### CODE REVIEW

**Comment by preda-bogdan** [comment]
I started the review process here however, I ran into a few issues when trying to replicate the stack. Will follow up wit the review as there are a few things to cover.

Until then I have a question about the implementation, wouldn't this also require changes on the Templates Cloud endpoint?

**Comment by cristian-ungureanu** [comment]
Thank you, Bogdan. There were only some minor changes on the server, no PR for now. I only needed to change https://github.com/Codeinwp/store-themeisle/blob/master/web/app/plugins/templates-cloud/inc/class-db-table.php#L173 with 
```
		if ( ! empty( $args['type'] ) ) {
			// Try to decode it.
			$decoded_array = json_decode( $args['type'], true );
			if ( ! empty( $decoded_array ) && is_array( $decoded_array ) ) {
				$args['type'] = $decoded_array;
			}
```

**Comment by preda-bogdan** [comment]
We decided to do some changes to ensure it is easier to test for the QA and do the review after the changes are finished.

**Comment by preda-bogdan** [comment]
I modified the code so that no other changes are required on the templates-cloud service, it will use the same existing infrastructure.

**Review by Soare-Robert-Daniel — APPROVED** [review]
Looking good. NIT: some console logs used for debugging left in the code

**Comment by preda-bogdan** [comment]
@irinelenache I've solved the issue with the toggle not counting on refresh, for the second issue we discussed it on our team and we decided it is the expected behavior for now and we can revisit it once we gather some more feedback from our users.

Once you have another look, let me know if everything is working as expected.

Thank you!

**Comment by irinelenache** [comment]
@preda-bogdan Tested and everything's fine now 🚀

**Pull request merged**
