### PR TITLE
Feat/cleanup import

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary
We now store the import changes inside a transient with a 24h lifetime.
After import a new option should be available on subsequent imports to cleanup the previous import:
image

If checked it should cleanup previous import before adding the new import.

### Test instructions
1. Import a new starter site.
2. Toggle the cleanup option on a new import.
3. Check that no settings from the first import are still present. (images, posts, categories, plugins etc.)

Closes Codeinwp/neve/issues/822

### CODE REVIEW

**Comment by gutoslv** [comment]
It's not removing neither deactivating the plugins after the cleanup.

You can check it here: https://spatial-shark.jurassic.ninja
User: demo 
pwd: 4DraG6cJq05n

**Comment by preda-bogdan** [comment]
@gutoslv Thank you for catching this. There was a typo on the plugins state from cleaning up the code that I've fixed. Can you see if the new build fixes the issue?

Thank you!

**Comment by gutoslv** [comment]
@preda-bogdan 
It's fixed now! Thanks!
But, I've found one issue with the WooCommerce
- [ ] When cleaning the previous import for a starter site with WooCommerce, it's does not remove the Cart, Shop and Checkout page created by WooCommerce. I think that would be a good idea to remove it also, since we are removing the WooCommerce plugin (only when it's imported by the previous starter site. It's not removing any plugin that was installed manually before the starter site).

**Comment by preda-bogdan** [comment]
> @preda-bogdan
> It's fixed now! Thanks!
> But, I've found one issue with the WooCommerce
> 
>     * [ ]  When cleaning the previous import for a starter site with WooCommerce, it's does not remove the Cart, Shop and Checkout page created by WooCommerce. I think that would be a good idea to remove it also, since we are removing the WooCommerce plugin (only when it's imported by the previous starter site. It's not removing any plugin that was installed manually before the starter site).

@gutoslv I will need some clarification here, since If I cleanup for after an import with WooComerce it will cleanup the plugin and the cart pages. Eg. from `Digital Store` to `Web Agency`. Was the WooComerce plugin available prior to the import? If yes this should be the expected behavior as I think it can cause issues if we decide to remove manually installed plugins.

An user could have already have set those pages and the WooComerce plugin and just testing imports could cause him to loose those.

Let me know if this is the case and if you have any feedback.
Thank you!

**Comment by gutoslv** [comment]
@preda-bogdan The WooCommerce plugin by default creates these 3 pages, so if the WooCommerce is installed for the first time by using the TPC, it'll create those pages, but it will not remove those pages when uninstalled. When the TPC install WooCommerce for the first time, after cleanup it should clear also these leftovers from WooCommerce.

My suggestion is: if removing WooCommerce plugin, also remove those 3 pages generated. If WooCommerce was already installed, don't remove those pages.

**Comment by preda-bogdan** [comment]
@gutoslv I've made some changes, the cleanup process will remove WooCommerce pages if the plugin is installed by an imported template. If the plugin exists prior to the import it will leave the pages and the plugin untouched.

Let me know if you find other issues or if it is working as expected.
Thank you for the feedback!

**Comment by gutoslv** [comment]
@preda-bogdan it's working fine! I'll move it to ready for merge, thanks for fixing it! 🚀

**Comment by HardeepAsrani** [comment]
Sam here. Should I merge it or anything left here?

**Comment by selul** [comment]
@HardeepAsrani let's keep it, I need to review it before.

**Pull request merged**
