### PR TITLE
Add sorting option to Template Library & Exporting to Elementor

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary
- Added sorting option which now allows you to change the order of the template by their date.
- Add "Save to Templates Cloud" to Elementor's context menu.
- Add Templates Library to Elementor.

Closes https://github.com/Codeinwp/templates-patterns-collection/issues/28

### CODE REVIEW

**Review by abaicus — CHANGES_REQUESTED** [review]
Looks good! Only a few things: 

There are some warnings inside the options page: 

image

---

Flex-basis inside the editor modal:

How it looks:
image

How it should look:
image

You can solve this by removing the flex-basis properties that you added and simply tweaking everything with flex-grow. Using flex-basis in such cases yields weird results as the items inside can be smaller than the set width.

- You can simply add `flex-grow: 1` to `.search-filters` and the search input inside it. 
- Then you can add a `margin-left: 20px` to the `.view-filters`.


---

I also think we can work on the source repo on different branches from now on, instead of forks. :+1: 

Otherwise, the checks will not run as expected and the ZIP file will not be built.

**Comment by abaicus** [comment]
Please do not forget to also make sure you don't forget to run `yarn run build && composer format` before committing. :see_no_evil:

**Comment by HardeepAsrani** [comment]
@abaicus Thanks for the review. I'll make these changes. It's still a work in progress so will let you know once you can review it fully.

**Comment by HardeepAsrani** [comment]
- The latest commit adds an 'orderby' select field so people can choose both the order and field to order by:

Screen Shot 2020-12-03 at 4 03 19 AM

- An export to cloud option to context menu:

Screen Shot 2020-12-03 at 4 05 00 AM

**Comment by selul** [comment]
@HardeepAsrani we can combine sorting order and sorting param into one dropdown, right now I need to do two clicks to view the preferred order. It's more smooth to have them in a single dropdown.

**Comment by HardeepAsrani** [comment]
You can do the final review @abaicus. Templates library for Elementor is empty so you can edit the **/elementor/src/data/templates-cloud/index.js** file and make `fetchTemplates` function to import Gutenberg type templates instead for it to work better for testing (of course, importing won't work for them but that you can test with custom templates).

Let me know if all seems fine with Elementor part.

**Comment by HardeepAsrani** [comment]
How things should look:
Screen Shot 2020-12-14 at 2 09 18 AM


Screen Shot 2020-12-14 at 2 09 10 AM

**Comment by HardeepAsrani** [comment]
All done, can you test @abaicus?

**Comment by HardeepAsrani** [comment]
Can you test @irinelenache? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] Clicking on the search icon ( https://prnt.sc/whhp31 ) doesn't trigger the search, i have to press enter for the search to work (don't know if this was intended or not)
- [ ] Now i can edit only the name of a template ( https://prnt.sc/whhyym https://prnt.sc/whhzh3 ) and after i do it, the order in the **Last modified** sorting remains the same ( https://prnt.sc/whi06x ) . So in **My library** the order in the **Date** and **Last modified** is the same
- [ ] One time this happened when i wanted to import a template named Irinel's template https://prnt.sc/whhbuq . I couldn't reproduce it a second time but thought you should know about it
- [ ] If i edit the name of an Elementor template ( https://prnt.sc/whiiw5 ) and then try to import it, it keeps loading and i get this error in console https://prnt.sc/whiihx

**Comment by HardeepAsrani** [comment]
```
 Clicking on the search icon ( https://prnt.sc/whhp31 ) doesn't trigger the search, i have to press enter for the search to work (don't know if this was intended or not)
```

That's by design, similar to how Google has an icon on left.

I'll be updating this comment as I go through changes and notify you in the end.

**Comment by HardeepAsrani** [comment]
@irinelenache Fixed everything. Can you test the ones you described so we could merge them? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] If i save a template that contains images, when i import it, the image isn't saved.
Gutenberg saved: https://prnt.sc/wiwnlz
Gutenberg imported: https://prnt.sc/wiwp0b
Elementor saved: https://prnt.sc/wiwjjp
Elementor imported: https://prnt.sc/wiwkyy

- [ ] Now i could reproduce the issue where the name contains special characters https://prnt.sc/wiwgrz https://prnt.sc/wiwtyf

**Comment by HardeepAsrani** [comment]
```
 If i save a template that contains images, when i import it, the image isn't saved.
Gutenberg saved: https://prnt.sc/wiwnlz
Gutenberg imported: https://prnt.sc/wiwp0b
Elementor saved: https://prnt.sc/wiwjjp
Elementor imported: https://prnt.sc/wiwkyy
```

Yea, if the image is local or remote access isn't allowed then we can't really access it.

**Pull request merged**
