### PR TITLE
fix: woo product import data Codeinwp/neve#3523

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary
Trigger product updates if imported to rebuild missing data from additional tables like `wc_product_meta_lookup`
Previously some data was not present unless an update was triggered, the data is being used in some block rendering.

### Test instructions

1. Import the Craft Beer Starter Site
2. On the Home Page, the Sale Products should be visible. See the screenshot below:
image

References: Codeinwp/neve/issues/3523.

### CODE REVIEW

**Comment by irinelenache** [comment]
@preda-bogdan Tested and the issue is fixed for the block you showed in the screenshot.
There is still a block under the **Popular products** title that renders as empty in the editor
editor: https://vertis.d.pr/Hdg4S7
frontend: https://vertis.d.pr/0KtYVr

If this particular issue is not related to this PR, we can move it to **Ready to merge** 🚀 

cc @mghenciu

**Comment by preda-bogdan** [comment]
@irinelenache Here I think there is an issue with the block itself, It will work only after changing to another display eg. Product Category > Craft Beer
@mghenciu Do you think we can change that to display the Product Category instead of Newest Product?

**Comment by mghenciu** [comment]
> Here I think there is an issue with the block itself, It will work only after changing to another display eg. Product Category > Craft Beer @mghenciu Do you think we can change that to display the Product Category instead of Newest Product?

Sorry for the late reply.
I've changed the Woo Blocks with Product Category: 
Screenshot 2022-07-28 at 14 18 15

**Comment by preda-bogdan** [comment]
Thank you!
This should work as expected now. 🚀

**Pull request merged**
