### PR TITLE
chore: added slack bot config to repo

### LINKED ISSUE #151: Add the slack announcement workflow
### Description:
Add the Slack announcement workflow as we have for other products for the channel #product-updates

### Alternatives:
Do nothing.

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary
Added the Slack announcement bot

Closes #151.

### CODE REVIEW

**Comment by selul** [comment]
@preda-bogdan you need to add those too https://github.com/Codeinwp/visualizer-pro/blob/master/.github/workflows/create-tag.yml#L30-L31

**Comment by preda-bogdan** [comment]
@selul thank you, are the SECRETS configured globally or will they need to be added per repo? I'm planning to create a similar PR for Neve and Neve Pro.

Thank you!

**Comment by selul** [comment]
I've enabled them for tpc, neve and neve pro

**Review by selul — APPROVED** [review]

**Comment by preda-bogdan** [comment]
Thank you, I will also create PRs for those.

**Pull request merged**
