### PR TITLE
Allow meta updating for users

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Allow meta updating for users: https://github.com/Codeinwp/templates-patterns-collection/issues/84
- Fix Custom Layouts editor crashing: https://github.com/Codeinwp/neve-pro-addon/issues/1337
- Fix Gutenberg sync update template for non-Gutenberg templates: https://github.com/Codeinwp/templates-patterns-collection/issues/88

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@mghenciu Can you test this? If using Neve, all the changes that you make to Neve's post settings (header display, title display, and other meta fields) should also be saved to the cloud and should import too (you need to preview the page to see the changes taking affect). It will happen for Elementor and Beaver too.

Make sure all imports work as expected and nothing fails. Try it without Publishing capabilities. Sorry for asking you to do QA work but you know this plugin best. 😄

**Comment by mghenciu** [comment]
Took a quick look now, @HardeepAsrani, and the Page Settings look ok for Elementor(so far)
Origin Elementor page: 
image

Imported Elementor Page:
image


For Beaver it **doesn't look to be working as expected**.
Origin Beaver:
image


Imported Beaver Page :
image


For Gutenberg pages, it would be implemented later?

**Comment by HardeepAsrani** [comment]
@mghenciu It's already there for Gutenberg too. Thanks, I'll take a look at Beaver.

**Comment by mghenciu** [comment]
Actually for Elementor & Beaver they look better (and it was the same before) compared to Gutenberg. Not sure if there is an issue with Gb, but the import doesn't look as expected.
Origin gb page: https://demosites.io/starter-sites-staging/about-5/
After import: https://annoyed-newt.jurassic.ninja/about-5-2/
About 5 – Neve Layout System _ 05-04-2021
About 5 – Annoyed Newt _ 05-04-2021

**Comment by HardeepAsrani** [comment]
@mghenciu I suppose you're using a different page template (full page template)?

**Comment by mghenciu** [comment]
> @mghenciu I suppose you're using a different page template (full page template)?

I was testing with Generic Pages, which is more or less the same thing as a 'normal' page, Saved and later imported from Cloud.

**Comment by HardeepAsrani** [comment]
Can you do that on Jurassic Ninja so I could see the difference between two pages? @mghenciu

**Comment by HardeepAsrani** [comment]
Wait, I can just check there. Thanks!

**Comment by HardeepAsrani** [comment]
Ignore last message. Can you send me creds to that jurassic instance?

**Pull request merged**
