### PR TITLE
Allow Page Templates Support

### LINKED ISSUE #89: Allow Page Templates saving
Save Page Template being used and import it accordingly.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary
Allow support to import/export WordPress' Page Templates meta as part of the full-page templates.

### Test instructions
You need to export and import in all editors and see that the page templates are exported/imported properly. Also, make sure to see there are never any errors.

Just to not confuse you, I'm talking about this:

Screenshot 2021-05-31 at 4 39 47 AM

It can also be accessed in Elementor from here:

Screenshot 2021-05-31 at 4 41 33 AM

In Beaver, it'll be the same as Block Template.

Closes #89

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Can you test it? @mghenciu  @irinelenache Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani can you provide some more test instructions, please?

**Comment by mghenciu** [comment]
I've tried on a jurassic instance, and this are my initial findings:
- Elementor looks good
- for Gutenberg the Template - Page Attributes, are not saved
here's how an imported page looks like: https://widespread-caterpillar.jurassic.ninja/services-5/
here's how it Should look: https://demosites.io/starter-sites-staging/services-5

- for Beaver Builder, the Template - Page Attributes is imported.
But (maybe that's coming in next releases), the Neve Options are not saved/imported properly.
Screenshot 2021-05-31 at 16 35 35

**Comment by HardeepAsrani** [comment]
@irinelenache Sorry if my instructions weren't proper.

Now Templates Cloud also imports/export your page's "Page Templates" field. The one where you can choose "Neve Fullwidth" and other style of Templates. Now you need to import/export and see if things work perfectly.

**Comment by HardeepAsrani** [comment]
@mghenciu For both Gutenberg & Beaver, can you list out what is indeed imported and what's not? Also, can you try by making a new template too and see so we know if this issue is with the current version or if it's a backward compatibility issue.

Thank you for the feedback. Everything is great with Elementor, right?

**Comment by mghenciu** [comment]
@HardeepAsrani 
For a **Newly saved** Gutenberg template, after import the Template - Page Attributes are **imported correctly**.
When importing **Existing** generic page templates (gb), the Template - Page Attributes are **not** imported correctly (tried with 2 pages and same thing).

For Beaver Builder,  **Template - Page Attributes** look good after import. 

For Elementor, **Template - Page Attributes** look good after import.


While testing this, I noticed that in My Library page, if the Edit button+icon have the Disabled state, there is a comma after the button (not sure if this is intended):
Screenshot 2021-06-02 at 11 54 05

Also wouldn't it be easier to Save a page (for each builder), import them, and then do a diff between origin of each page and what was imported? instead of doing it manually for each property

**Comment by irinelenache** [comment]
@HardeepAsrani On Elementor, if i set a a page template (for example Elementor canvas) and save it, when i import the page, the page layout is `Page builder full width (Neve)`
The page i created: https://inadequate-gayal.jurassic.ninja/test-elementor-template/
The page i imported: https://inadequate-gayal.jurassic.ninja/test-elementor-template-2/

If you want to access it: `demo   oMPTCO0Bzl6Y`

**Comment by HardeepAsrani** [comment]
@irinelenache I tried to make a new page and imported your template seems to work just fine. No issue at all on my end.

**Comment by HardeepAsrani** [comment]
@mghenciu 

> When importing Existing generic page templates (gb), the Template - Page Attributes are not imported correctly (tried with 2 pages and same thing).

It's working fine for me. The meta is being updated but isn't reflected instantly. You can try to save the page and refresh to see. I've fixed this delay in Neve already and it was merged to developed branch few days back, fix should be out soon on main branch too.

@irinelenache Does it work for you when you import Service 5 template from Templates Cloud on to a page with Neve+Pro?

**Comment by HardeepAsrani** [comment]
I was doing some testing and there was this bug where if you import Elementor or Gutenberg section template, it was crashing the editor. The above comment fixes it, so please make sure I haven't missed anything else before it's released. 👯

**Comment by irinelenache** [comment]
@HardeepAsrani When i import **Services 5** template it looks like this https://prnt.sc/14iw414
Besides of this, looks like it works fine

**Comment by HardeepAsrani** [comment]
Seems normal @irinelenache thanks.

@mghenciu Any update? 😄

**Comment by mghenciu** [comment]
> Seems normal @irinelenache thanks.
> 
> @mghenciu Any update? 😄

My update is the same as before :)
The Gutenberg pages don't have the Template: **Default template**, under Page Attributes. After import the pages are **Page Builder Full Width** (Neve), and as Irinel mentioned, this is how [Services 5](https://necked-snake.jurassic.ninja/services-5/) page looks like after import (normally the page should be contained to 1170px or around that):
image

I also tried Saving a new page in My Library, and same result.

Not sure if that's the case, but maybe when I set Template: **Default template**, and publish a page, this means the page will inherit the Default template of the Theme where it's imported. And after you import it on an instance where Neve is installed, the page becomes **Page Builder Full Width** (Neve).

TDLR, the Gutenberg pages should have the page content Contained after import, otherwise the layout breaks.
Left side how's the origin and right side is the imported page:
image

**Comment by HardeepAsrani** [comment]
Thanks for the update @mghenciu. I'll see what could be the issue.

**Comment by mghenciu** [comment]
Any news on this @HardeepAsrani ? for the Page Attributes > Template option

**Comment by HardeepAsrani** [comment]
@mghenciu It's part of this https://github.com/Codeinwp/templates-patterns-collection/pull/103, I'm waiting for #93 & #94 to be merged so we can release them together as they contain some good fixes, especially Woo fix. Should I wait or release it now? @selul

**Comment by selul** [comment]
we can go ahead

**Pull request merged**
