### PR TITLE
Feat/sparks install dde

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Allow Themeisle plugins to be installed.
This requires https://github.com/Codeinwp/demo-data-exporter/pull/146 to be merged into development.

### Test instructions

1. Use `staging.demosites.io` to test.
2. Check using https://staging.demosites.io/jewellery-shop-gb that Sparks is installed on the import.

Closes Codeinwp/demo-data-exporter#129.

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

**Comment by preda-bogdan** [comment]
@irinelenache This can now be tested with `staging.demosites.io`

**Comment by irinelenache** [comment]
@preda-bogdan Tested using this PR and staging demosites, and images are no longer imported https://vertis.d.pr/i/UymCPV (Tried with Jewellery shop and other demos)

Regarding the Sparks install, it works fine, but i wonder if we can also activate its license when it's installed, because it uses the Neve pro license.
Let me know what you think 🙏 

You can check the issues here:
```
https://tpctest.vertisite.cloud
Username: vutubuvumi0213
Password: ZwGhiBTKqmsFaR61Vlyf
```

**Comment by preda-bogdan** [comment]
@irinelenache can you try to re-import the site? There was a wrong path set on staging, it should import the images correctly now.

With regards to activating the Sparks license it should automatically inherit the one from Neve Pro and that should be handled by the Sparks plugin on activation.

**Comment by irinelenache** [comment]
@preda-bogdan Checked again on a fresh instance and the issue persists for the Jewellery starter site, the images still aren't imported 

You can check here:
```
URL: https://tcpfresh.vertisite.cloud
Username: dabemasuzu6657
Password: 3zF5TxrEv0MUaDl6Qebu
```

Besides this, i tried to check if the import works on a Tastewp instance, and there i can't even start the import and i'm getting an [error](https://vertis.d.pr/i/l6kmlr) related to the previous instance (probably because i used the same Neve pro license). Here is the second instance, maybe it will help for the debugging:
```
 Admin area URL: https://testtpc.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: yhNgbeZ7CcA 
```

**Comment by preda-bogdan** [comment]
@irinelenache I checked both instances and the import worked. For the first one, I think when you tested the response you got was cached. Now it worked as expected.

For the second instance, there was an issue with `staging.demosites.io` instance as Varnish would cache the response and would return the wrong Origin. On production, this is handled by lambda. Here I had to disable varnish.
After that, the import worked as expected.

When you get around do another round of testing as these issues were related to the server configurations and not the PR. Let me know if now everything works as expected.

Thank you!

**Comment by irinelenache** [comment]
@preda-bogdan Tested again and everything's fine now, thanks for explaining the issues 🚀

**Pull request merged**
