### PR TITLE
Improve no template screen

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Test instructions

- 
- 

Closes #.

### CODE REVIEW

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani is this ready for the release?

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu No, I wasn't working all those days. Let me finish it now.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu Rest added. I didn't do the function like here https://github.com/Codeinwp/templates-cloud/issues/35#issuecomment-1005532382 as Ionut said we shouldn't display a different message. Let me know if there is anything left.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and it seems to work fine, found some small things only:

- [ ] Can we have some margin bottom [here](https://vertis.d.pr/usUCjy) like the one [on top](https://vertis.d.pr/BsTT38)?
- [ ] Shouldn't the text [here](https://vertis.d.pr/U2DzT0) be Templates Cloud?

**Comment by HardeepAsrani** [comment]
@irinelenache Done!

**Comment by irinelenache** [comment]
@HardeepAsrani The margin problem is fixed, thank you 👍 
The changed text is now **_Unlock the Template Clouds features..._** , it should be **_Unlock the Templates Cloud features..._**

**Comment by cristian-ungureanu** [comment]
@irinelenache fixed it. Is there anything else?

**Comment by HardeepAsrani** [comment]
Very satisfying to see a botched to fix a grammar mistake and made it worse. 😆

**Comment by irinelenache** [comment]
@HardeepAsrani @cristian-ungureanu No other bugs from my side, this can be merged after all checks are passing 👍

**Pull request merged**
