### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Rename to **Save to Templates Cloud** to **Neve Cloud**
- Improve search based on #60
- Fix Sync button layout on hover #36
- Improve how we handle template name #70
- Associate template with Meta #41 
- Activate Elementor/Beaver if importing respective templates #53

### CODE REVIEW

**Comment by mghenciu** [comment]
@Codeinwp/qa-team,
 fyi, I've tested & left some comments for #60 & #53.

**Comment by HardeepAsrani** [comment]
Thanks @mghenciu! I've fixed the plugin import message. @irinelenache can you do the final testing too to make sure we didn't miss anything?

**Comment by irinelenache** [comment]
@HardeepAsrani everything works fine on my end except the padding mentioned here https://github.com/Codeinwp/templates-patterns-collection/issues/60#issuecomment-814882275 and i didn't find the name change to **Neve cloud**, maybe i'm not using it correctly?

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache. The name change is only in "Save to" buttons.

**Comment by irinelenache** [comment]
@HardeepAsrani On Beaver Builder it is changed, on Gutenberg it still looks like this https://prnt.sc/11804lv and on Elementor it looks like this https://prnt.sc/11806sw . Let me know if i missed something

**Pull request merged**
