### PR TITLE
Template cloud

### PR DESCRIPTION
**Pull request by abaicus**
### Summary
Adds template cloud functionality:

# Test instructions

I've added some templates for testing purposes, but these are not the ones that will be published.

### Editor:
- There should be a Templates Cloud block that will allow inserting only Page Templates.

### Starter Sites Page:
- There should be a new menu listing `Page templates`. 
- You should be able to preview/import the templates under that.
- The Gutenberg Web Agency should have a new button that allows you to view all the individual pages.
- You should be able to preview, import those
- Everything on the screen should do what you expect
- Starter sites should still work as they did.

---

## Pro Agency License

You'll need [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/1032) from Neve Pro for it to work properly.

### Editor:
- There should be a new sidebar that allows publishing your own templates to the cloud.
- There should be a new tab inside the Templates Cloud block - `My templates` that should allow importing/previewing the users' uploaded templates 

### Starter Sites Page:
- There should be a new My Library page that allows importing the user templates.

---

## Checklist before release:

- [ ] Remove the flag from the Gutenberg Web Agency plugin.
- [ ] Remove all templates from the database.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
- [ ] the RTL CSS file doesn't load

download

- [ ] Maybe when importing/previewing Page Templates there could be a mention that Otter blocks needs to be installed?
download (1)

**Comment by abaicus** [comment]
@rodica-andronache 

>  Maybe when importing/previewing Page Templates there could be a mention that Otter blocks needs to be installed?
We decided against this for this version.

**Comment by rodica-andronache** [comment]
- [ ] When you are in the preview mode of one of the page templates from My Library, clicking on Page Templates doesn’t work (until you click on Close Preview), even though it looks like a link that you can click on https://prnt.sc/vlew71

- [ ] Also the entire popup window that appears when you use the Templates Cloud block, can be closed only if you click not he X button. Maybe it would be a good idea for it to close when you click outside the window too.

- [ ] https://www.loom.com/share/028d544a8eb744409b91b803e2b0ab84 - renaming Page templates doesn’t apply until I refresh the page. This happens just in the List view. In Grid is working well.

- [ ] Same issue if I rename the page template in Grid view ( the name gets updated correctly ). But if I switch to List view, without refreshing the page, the new name doesn’t appear.

- [ ] Importing a duplicated page template, imports a blank page template https://www.loom.com/share/3c57828040a94f95bb54ee1ebb50e4fb

**Comment by rodica-andronache** [comment]
- [ ] when you click on the `Save Page as Template` button for `Custom Layouts` or for `Courses` for example ( from `LifterLMS` ), the page is saved, but a notice appears` Cannot read property 'set' of null`


- [ ] not sure if this was wanted or not, but the layout for the onboarding screen changed a bit (it's not boxed anymore).
How it is now, in this PR

How it is in the current version
download

**Comment by abaicus** [comment]
@rodica-andronache Thanks for taking a look! :+1: 

>  Importing a duplicated page template, imports a blank page template https://www.loom.com/share/3c57828040a94f95bb54ee1ebb50e4fb

For now, I've removed the duplication functionality. It doesn't make that much sense ATM as you can't really replace the content inside the template.

**Comment by rodica-andronache** [comment]
@abaicus checked again and everything is fixed now 👍 Just saw an issue with the header, on the Starter Sites page, when you migrate from Zelle Lite
download

**Comment by abaicus** [comment]
@rodica-andronache I've disabled the sticky header when the migration is active. It will work fine after a refresh. :+1:

**Comment by rodica-andronache** [comment]
@abaicus in the sticky header is not possible to enter a word ( after each character, the focus jumps off the input ) https://www.loom.com/share/55d855fcb59c47d4be391b9fa3b3f9b9

**Comment by abaicus** [comment]
@rodica-andronache It should work fine now 👍

**Pull request merged**
