### PR TITLE
Add Beaver Builder integration

### PR DESCRIPTION
**Pull request by HardeepAsrani**
There was an issue with merging the Beaver branch to the Development branch so I had to make a new branch for this.

You can test it @mghenciu @irinelenache to see how it works. Here are two ways to open the Templates Cloud modal:
Screen Shot 2021-03-08 at 6 31 05 AM

If you open it from the menu on left, the default tab will be to save the page to the cloud. Also, if you import anything it will be appended to the last position of the page.

Screen Shot 2021-03-08 at 6 31 31 AM

If you import by adding a block, the imported template will be imported to the position where you dragged the module.

You can also export a particular row from here:

Screen Shot 2021-03-08 at 6 36 09 AM

Let me know how it works. Also, you currently can't import from the Admin page but I'll fix that too.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Now you should be able to import it from Admin Page too.

**Comment by irinelenache** [comment]
@HardeepAsrani  the integration seems to work fine, i found these small things:

- [ ] The icons used for sorting ascending/descending look like this https://prnt.sc/10h7vn8
- [ ] When saving a template, i couldn't click on the name field to change the name (i don't know if it's expected or not)
 https://www.loom.com/share/71609e4d5ec74c17b9842b4bca0d07d1

**Comment by HardeepAsrani** [comment]
> The only small thing I noticed (probably not an issue) are the bottom and right scroll bars; they appear when you hover on the Display icons (even when the page has no Templates to import):

Yea, I noticed that too but can't really do much to solve that. :(

**Comment by tudor-themeisle** [comment]
I have the same behaviour, as @irinelenache, and also I tried to export to template cloud but I receive an Export Failed message ( https://prnt.sc/10hvvfa ). 

In my test, the icons used for sorting ascending/descending look like this  ( https://prnt.sc/10hvzw8 )

**Comment by irinelenache** [comment]
> > The icons used for sorting ascending/descending look like this https://prnt.sc/10h7vn8
> 
> This seems like a weird one. Can you get someone else with Windows to check too? I don't have Windows so it's hard to reproduce it but seems to be more of an issue with your particular instance. So it'll be better if we can double-check it. Thank you!

@HardeepAsrani I tried to replicate it again on another instance and i couldn't do it, if i encounter the problem again i'll let you know

**Comment by HardeepAsrani** [comment]
Hey @tudor-themeisle,

Did you have Neve Pro installed?

**Comment by tudor-themeisle** [comment]
@HardeepAsrani, Yes I have Neve Pro installed.

**Comment by HardeepAsrani** [comment]
Can anyone else reproduce this issue? https://github.com/Codeinwp/templates-patterns-collection/pull/68#issuecomment-795136976 @irinelenache @mghenciu?

Or can you @tudor-themeisle reproduce it again on an online website (like tastewp.com) so I could check? Thank you!

**Comment by tudor-themeisle** [comment]
> Can anyone else reproduce this issue? [#68 (comment)](https://github.com/Codeinwp/templates-patterns-collection/pull/68#issuecomment-795136976) @irinelenache @mghenciu?
> 
> Or can you @tudor-themeisle reproduce it again on an online website (like tastewp.com) so I could check? Thank you!

Hi @HardeepAsrani, yes, I will reproduce it again and send you the instance with the credentials. 

Thank you.

**Comment by tudor-themeisle** [comment]
> Can anyone else reproduce this issue? [#68 (comment)](https://github.com/Codeinwp/templates-patterns-collection/pull/68#issuecomment-795136976) @irinelenache @mghenciu?
> 
> Or can you @tudor-themeisle reproduce it again on an online website (like tastewp.com) so I could check? Thank you!

Hi @HardeepAsrani, I recreated the instance again, here are the credentials:

internet Site name: Cagey Society
URL: https://cageysociety.tastewp.com
Username: tud
Password: 1KdJYaockx8

**Pull request merged**
