### PR TITLE
Sync button layout on hover

### LINKED ISSUE #36: Sync button layout on hover on mac 12inch
On hover, the text "Sync" appears, and it's not vertically aligned on a 12inch mac.
Screenshot (1)

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
### Summary
It seems like in older Safari browsers ( maybe chrome too, Rodica said it was present there too) the paddings of ::before / ::after does not merge with the padding of their parent. Removing the padding-top and padding-bottom fixed the issue.

### Test instructions
This issue needs to be tested on BrowserStack if you have the latest version of Safari. It happens on 13.1 or lower
- Install neve, neve pro and template clouds
- Go to Dashboard -> Starter sites -> My Library and hover over the Sync button
- If the button doesn't appear, you might need a license that has the library enabled.

Closes #36.

### CODE REVIEW

**Comment by tudor-themeisle** [comment]
The fix is working.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu anything left here or should we merge it?

**Comment by cristian-ungureanu** [comment]
I fixed the conflicts so you can merge it but it seems it's still in the QA column so maybe they want to test it more. 
cc. @tudor-themeisle, @irinelenache

**Comment by tudor-themeisle** [comment]
> I fixed the conflicts so you can merge it but it seems it's still in the QA column so maybe they want to test it more.
> cc. @tudor-themeisle, @irinelenache

I think we can merge this. Let's see what @irinelenache says about it.

**Comment by irinelenache** [comment]
@cristian-ungureanu @HardeepAsrani sorry, the PR works fine and can be merged. I saw this comment https://github.com/Codeinwp/templates-patterns-collection/issues/36#issuecomment-801151020 and thought we have to wait for a response

**Pull request merged**
