### PR TITLE
Fix/bug 81

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary
Re-map categories if placeholders are present.
References: Codeinwp/templates-patterns-collection#81

### Test instructions
Use the Gist here: https://gist.github.com/preda-bogdan/f4d1b4e876ecc9424e98b837dc8519b5

1. Install Neve on a new instance
2. Download the gist from above as .zip and install and activate as a plugin
3. Use the plugin build from this branch to test

**NOTE:** The plugin from GIST should already be active since we save the sites list inside a 12h transient.

The changes from from https://github.com/Codeinwp/demo-data-exporter/pull/78 are already present on the staging instance: https://demosites.io/

When importing the Digital Store template it should map the categories correctly.

It should replace all the block categories placeholders with the correct imported categories.
The format used is `replace_cat_%d`.

### Testing Instance example:
I went ahead and did all the steps above here:

```
 Admin area URL: https://test-staging-imp.tastewp.com/wp-admin 
 Username: bogdanpreda 
 Password: HCSC-l4aZqc 
```

You can use it as an example but please test on you own instances.

### CODE REVIEW

**Comment by gutoslv** [comment]
I'm still getting the same error :<

Environment: https://little-hoopoe.jurassic.ninja/wp-admin/
user: demo
pwd: 5C1s8G0LxKrg

Also, I'm getting a new error when going to the home page for editing, it's this one: https://vertis.d.pr/3Z3n9l

**Comment by preda-bogdan** [comment]
@gutoslv Hello
I've updated the information for testing here: https://github.com/Codeinwp/templates-patterns-collection/pull/94#issue-649951242

You should be able to test now using the staging where I have already updated the demo-export.
Let me know if you encounter any issues or require any clarifications.

Thank you!

**Comment by gutoslv** [comment]
@preda-bogdan Tested and it's working fine! Moved to Ready to Merge!

**Comment by HardeepAsrani** [comment]
Should I merge it or anything left here to do @preda-bogdan?

**Comment by selul** [comment]
@HardeepAsrani let's keep it, I need to review it before.

**Pull request merged**
